- name: Ensure apt cache is updated
  apt:
    update_cache: yes

- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Deploy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Ensure NGINX running
  service:
    name: nginx
    state: started
    enabled: yes
